export enum EOpenAIModel {
	GPT_35_TURBO = "gpt-3.5-turbo",
	GPT_4_TURBO = "gpt-4-turbo",
	GPT_4_TURBO_PREVIEW = "gpt-4-turbo-preview",
	GPT_4O = "gpt-4o",
	GPT_4O_MINI = "gpt-4o-mini",
	GPT_5 = "gpt-5",
	GPT_5_1 = "gpt-5.1",
	GPT_5_1_CODEX = "gpt-5.1-codex",
	GPT_5_1_CODEX_MAX = "gpt-5.1-codex-max",
	GPT_5_1_CODEX_MINI = "gpt-5.1-codex-mini",
	GPT_5_2 = "gpt-5.2",
	GPT_5_2_PRO = "gpt-5.2-pro",
	GPT_5_CODEX = "gpt-5-codex",
	GPT_5_MINI = "gpt-5-mini",
	GPT_5_NANO = "gpt-5-nano",
	GPT_5_PRO = "gpt-5-pro",
	O1 = "o1",
	O1_MINI = "o1-mini",
	O1_PREVIEW = "o1-preview",
	O1_PRO = "o1-pro",
	O3 = "o3",
	O3_MINI = "o3-mini",
	O3_PRO = "o3-pro",
	O4_MINI = "o4-mini",
}
